### ISSUE TITLE
Slow as $%#T! 💩 

### ISSUE THREAD

**Issue by e6** [Exo-OX1564/dmdelete#1]
My hand deletes messages faster. 🤣

**Comment by Exo-OX1564** [comment]
> My hand deletes messages faster. 🤣

By the way you're talking, it seems as if you're trying to use this for unsolicited purposes!
May I remind you that this is educational only, and was put on public to show users, there is no way a real one would be out on public for unsolicited purposes, seeming as if that's yout intention!

Also, please do remember discord now has a 5/5 requests based limit, so whatever you're planning isn't going to work.
