### ISSUE TITLE
You literally exposed yourself mate. 

### ISSUE THREAD

**Issue by e6** [Exo-OX1564/dmdelete#2]
Only someone that has abused Discord's API and broken the ToS would have their bot flagged, as you stated in the README.md.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/3921464/224504045-318ea432-0a0f-4884-a8f2-87df8fc3360c.png">

**Comment by Exo-OX1564** [comment]
What? If you've read the discord developer docs on api limits, then you would know? It seems like you're talking with no experience on discord docs nor the actual code itself.

**Comment by Exo-OX1564** [comment]
> > What? If you've read the discord developer docs on api limits, then you would know? It seems like you're talking with no experience on discord docs nor the actual code itself.
> 
> The Discord API doesn't explicitly state anything about the limits of deleting messages before being flagged.
> 
> Your lies are too blatant lmao

Defo is on requests, and if you code you'd know requests work the same even with deleting messages.

**Comment by Exo-OX1564** [comment]
Just incase your ideology needs it:
![image](https://user-images.githubusercontent.com/95084482/224561210-d1158d06-33cb-4b46-9df4-be11b032eeb4.png)

Reference: https://discord.com/developers/docs/topics/rate-limits
😭 Nice try.
