### ISSUE TITLE
Skid.

### ISSUE THREAD

**Issue by e6** [Exo-OX1564/dmdelete#3]
Just incase your ideology needs it:
![image](https://user-images.githubusercontent.com/95084482/224561210-d1158d06-33cb-4b46-9df4-be11b032eeb4.png)

Reference: https://discord.com/developers/docs/topics/rate-limits
😭 Nice try.

_Originally posted by @Exo-OX1564 in https://github.com/Exo-OX1564/dmdelete/issues/2#issuecomment-1465252403_
            
That's not related at all buddy. You and "incog" and XXL are just skids 😂

**Comment by Exo-OX1564** [comment]
LOL. Eric should have known it was you, the shittttttyyyy skid. That is
related,you're clearly not a coder and needed help with a v11 code lmaooo.
Besides, you made skid wiki which in fact just covers all the people you're
jealous of. Publicity for me, just grow up!!!!
Besides, you added your alt accounts as "witnesses" last time you tried
coding with me on a vc so the person who really crapped up was you! Nice
try though.

**Comment by Exo-OX1564** [comment]
You're too pathetic spending your life on discord these days making your ego too damnnnn.
